name: Rofood-cypress

on:
 
   schedule:
    # * is a special character in YAML so you have to quote this string '0 1 * * *'
     - cron:  "0 1 * * *"
  
   push:
      branches: ["main"]

   
     
  
jobs:
   test:
      runs-on: macos-latest
      steps:
         - uses: actions/checkout@v3
         - uses: cypress-io/github-action@v4
        
           with:
              record: true
           env:
              CYPRESS_RECORD_KEY: fc789b79-e818-43a1-ba48-7a632f550ff5