name: Rofood-cypress
on:
  schedule:
    - cron: '0 14 * * 1'
   push:
      branches: ["main"]

  
  
jobs:
   test:
      runs-on: macos-latest
      steps:
         - uses: actions/checkout@v3
         - uses: cypress-io/github-action@v4
           with:
              record: true
           env:
              CYPRESS_RECORD_KEY: 4eb97121-e822-4fde-a955-02494b8c3cef